# ARTI 308 – Machine Learning Lab 2
## Identifying ML Problems, Selecting Open Datasets, and Drawing a Methodology Diagram

**Academic Year:** 2025/2026 – 2nd Semester  
**Dataset:** Pima Indians Diabetes Dataset  
**Problem Type:** Binary Classification

---
## Part 1: Dataset Selection

**Dataset chosen:** Pima Indians Diabetes Dataset  
**Source:** UCI Machine Learning Repository / Kaggle  
**Link:** https://www.kaggle.com/datasets/uciml/pima-indians-diabetes-database

This dataset contains medical records of female patients (Pima Indian heritage) and is used to predict diabetes diagnosis.

---
## Part 2: Machine Learning Problem Definition

**Problem Type:** Binary Classification  
**Target Variable:** `Outcome` (0 = No Diabetes, 1 = Diabetes)  

**Problem Statement:**  
Given medical diagnostic measurements (glucose level, BMI, age, blood pressure, etc.) for female patients, predict whether a patient has diabetes or not.

**Why is this Classification (not Regression or Clustering)?**  
- The output (`Outcome`) is a **discrete categorical label** (0 or 1), not a continuous number → so it is NOT regression  
- We have **labeled data** (each row already has a known outcome) → so it is NOT clustering  
- We are predicting one of two categories → this is **binary classification**

---
## Part 3: Loading and Inspecting the Dataset

In [9]:
# Import required library
import pandas as pd

In [10]:
# Load the dataset
# Download from: https://www.kaggle.com/datasets/uciml/pima-indians-diabetes-database
url = 'https://raw.githubusercontent.com/jbrownlee/Datasets/master/pima-indians-diabetes.data.csv'

column_names = [
    'Pregnancies', 'Glucose', 'BloodPressure', 'SkinThickness',
    'Insulin', 'BMI', 'DiabetesPedigreeFunction', 'Age', 'Outcome'
]

df = pd.read_csv(url, names=column_names)
print("Dataset loaded successfully!")

Dataset loaded successfully!

In [11]:
# 1. Display the shape (rows, columns)
print("Dataset Shape:")
print(f"  Rows (patients): {df.shape[0]}")
print(f"  Columns (features): {df.shape[1]}")

Dataset Shape:
  Rows (patients): 768
  Columns (features): 9

In [12]:
# 2. Preview the first 5 rows
print("First 5 rows of the dataset:")
df.head()

First 5 rows of the dataset:

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1

In [13]:
# 3. Check column names and data types
print("Column names and data types:")
print(df.dtypes)

Column names and data types:
Pregnancies                   int64
Glucose                       int64
BloodPressure                 int64
SkinThickness                 int64
Insulin                       int64
BMI                         float64
DiabetesPedigreeFunction    float64
Age                           int64
Outcome                       int64
dtype: object

In [14]:
# 4. Basic dataset information
print("Dataset Info:")
df.info()

Dataset Info:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 768 entries, 0 to 767
Data columns (total 9 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Pregnancies               768 non-null    int64
 1   Glucose                   768 non-null    int64
 2   BloodPressure             768 non-null    int64
 3   SkinThickness             768 non-null    int64
 4   Insulin                   768 non-null    int64
 5   BMI                       768 non-null    float64
 6   DiabetesPedigreeFunction  768 non-null    float64
 7   Age                       768 non-null    int64
 8   Outcome                   768 non-null    int64
dtypes: float64(2), int64(7)
memory usage: 54.1 KB

In [15]:
# 5. Check target variable distribution
print("Target Variable Distribution (Outcome):")
print(df['Outcome'].value_counts())
print(f"\n0 = No Diabetes: {df['Outcome'].value_counts()[0]} patients")
print(f"1 = Diabetes:     {df['Outcome'].value_counts()[1]} patients")

Target Variable Distribution (Outcome):
Outcome
0    500
1    268
Name: count, dtype: int64

0 = No Diabetes: 500 patients
1 = Diabetes:     268 patients

In [16]:
# 6. Basic statistical summary
print("Statistical Summary:")
df.describe()

Statistical Summary:

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
count,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000
mean,3.845052,120.894531,69.105469,20.536458,79.799479,31.992578,0.471876,33.240885,0.348958
std,3.369578,31.972618,19.355807,15.952218,115.244002,7.884160,0.331329,11.760232,0.476951
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.078000,21.000000,0.000000
25%,1.000000,99.000000,62.000000,0.000000,0.000000,27.300000,0.243750,24.000000,0.000000
50%,3.000000,117.000000,72.000000,23.000000,30.500000,32.000000,0.372500,29.000000,0.000000
75%,6.000000,140.250000,80.000000,32.000000,127.250000,36.600000,0.626250,41.000000,1.000000
max,17.000000,199.000000,122.000000,99.000000,846.000000,67.100000,2.420000,81.000000,1.000000

---
## Part 4: Methodology Diagram

The methodology diagram for this project is saved as **`methodology_diagram.png`** in this repository.

The workflow follows these steps:

1. **Dataset Selection** → Choose Pima Diabetes dataset from Kaggle/UCI  
2. **Data Loading** → Load CSV using Pandas  
3. **Data Preprocessing** → Handle zero values, normalize features, encode if needed  
4. **Train/Test Split** → Split data 80% train / 20% test  
5. **Model Training** → Train classification models (Logistic Regression, Random Forest, etc.)  
6. **Model Evaluation** → Evaluate using Accuracy, Precision, Recall, F1-Score  
7. **Results** → Compare models and report best performance